CC      = gcc
CFLAGS  = -Wall -Wextra -std=c99 -Iinclude -g
BUILD_DIR = build

.PHONY: all clean help

all:
	@echo "Hãy implement rước khi build!"

clean:
	rm -rf $(BUILD_DIR)

help:
	@echo "Makefile cho bản luyện tập"
